CREATE USER root WITH PASSWORD 'root';

CREATE TABLE public."FeedbackResponses" (
    "FeedbackId" integer NOT NULL,
    "Id" integer NOT NULL,
    "Content" text,
    "FeedbackResponseDate" text
)
TABLESPACE pg_default;

--
-- TOC entry 210 (class 1259 OID 22360)
-- Name: FeedbackResponses_FeedbackId_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."FeedbackResponses" ALTER COLUMN "FeedbackId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."FeedbackResponses_FeedbackId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TOC entry 213 (class 1259 OID 22369)
-- Name: Feedbacks; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Feedbacks" (
    "Id" integer NOT NULL,
    "Content" text,
    "FeedbackDate" text,
    "HospitalName" text
)
TABLESPACE pg_default;
--
-- TOC entry 212 (class 1259 OID 22368)
-- Name: Feedbacks_Id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."Feedbacks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Feedbacks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 22377)
-- Name: Hospitals; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Hospitals" (
    "Id" integer NOT NULL,
    "HospitalName" text,
    "HospitalAddress_Street" text,
    "HospitalAddress_City" text,
    "HospitalConnectionInfo_Url" text,
    "HospitalConnectionInfo_ApiKey" text
)
TABLESPACE pg_default;


ALTER TABLE public."Hospitals" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Hospitals_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 22385)
-- Name: Medicines; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Medicines" (
    "Id" integer NOT NULL,
    "Name" text,
    "Manufacturer" text,
    "MedicineType" integer NOT NULL,
    "Description" text,
    "IsPrescribed" boolean NOT NULL,
    "SideEffects" text,
    "RecommendedDose" text,
    "Intensity" double precision NOT NULL,
    "Quantity" integer NOT NULL
)

TABLESPACE pg_default;




ALTER TABLE public."Medicines" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Medicines_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 22393)
-- Name: Notifications; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Notifications" (
    "Id" integer NOT NULL,
    "Title" text,
    "Content" text,
    "Date" timestamp without time zone NOT NULL,
    "Name" text,
    "Read" boolean NOT NULL
)

TABLESPACE pg_default;


ALTER TABLE public."Notifications" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Notifications_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 22401)
-- Name: Offers; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Offers" (
    "Id" integer NOT NULL,
    "Title" text,
    "Content" text,
    "OfferDateRange_StartDate" timestamp without time zone,
    "OfferDateRange_EndDate" timestamp without time zone
)

TABLESPACE pg_default;

--
-- TOC entry 220 (class 1259 OID 22400)
-- Name: Offers_Id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."Offers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Offers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 22409)
-- Name: TenderItems; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."TenderItems" (
    "Id" integer NOT NULL,
    "Name" text,
    "Quantity" integer NOT NULL,
    "TenderId" integer NOT NULL
)

TABLESPACE pg_default;

--
-- TOC entry 222 (class 1259 OID 22408)
-- Name: TenderItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."TenderItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TenderItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 22417)
-- Name: TenderOfferItems; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."TenderOfferItems" (
    "Id" integer NOT NULL,
    "Name" text,
    "Quantity" integer NOT NULL,
    "Price" double precision NOT NULL,
    "TenderOfferId" integer NOT NULL
)
TABLESPACE pg_default;

--
-- TOC entry 224 (class 1259 OID 22416)
-- Name: TenderOfferItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."TenderOfferItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TenderOfferItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 22425)
-- Name: TenderOffers; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."TenderOffers" (
    "Id" integer NOT NULL,
    "TenderId" integer NOT NULL,
    "PharmacyName" text,
    "isWinner" boolean NOT NULL,
    "CreationDate" timestamp without time zone NOT NULL
)
TABLESPACE pg_default;

--
-- TOC entry 226 (class 1259 OID 22424)
-- Name: TenderOffers_Id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."TenderOffers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TenderOffers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 22433)
-- Name: Tenders; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Tenders" (
    "Id" integer NOT NULL,
    "CreationDate" timestamp without time zone NOT NULL,
    "StartDate" timestamp without time zone NOT NULL,
    "EndDate" timestamp without time zone NOT NULL,
    "HospitalApiKey" text,
    "HospitalTenderId" integer NOT NULL,
    "Opened" boolean NOT NULL
)

TABLESPACE pg_default;

--
-- TOC entry 228 (class 1259 OID 22432)
-- Name: Tenders_Id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."Tenders" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tenders_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

GRANT ALL ON DATABASE drugstoredb TO root;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO root;

--
-- TOC entry 209 (class 1259 OID 22355)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: root
--
INSERT INTO public."Medicines"(
	"Id", "Name", "Manufacturer", "MedicineType", "Description", "IsPrescribed", "SideEffects", "RecommendedDose", "Intensity", "Quantity")
	VALUES (1, 'Brufen', 'Galenika', 0, 'Due to its analgesic effects, ibuprofen is indicated for the relief of mild to moderate pain.', false, 'Nausea, vomiting, diarrhea, flatulence, constipation, dyspepsia, abdominal pain, melena, haematemesis, ulcerative stomatitis, exacerbation of colitis and Crohns disease', '3x1', 800, 75);
INSERT INTO public."Medicines"(
	"Id", "Name", "Manufacturer", "MedicineType", "Description", "IsPrescribed", "SideEffects", "RecommendedDose", "Intensity", "Quantity")
	VALUES (2, 'Paracetamol', 'Galenika', 1, 'Mild analgesic. The use of tablets is recommended for the treatment of painful and febrile conditions.', false, 'Special care should be taken when using paracetamol in patients with reduced liver function or
kidney. The risk of overdose is higher in patients with liver disease resulting from abuse
alcohol, and is not accompanied by cirrhosis of the liver.
The recommended dose should not be exceeded.', '3x1', 500, 80);
INSERT INTO public."Medicines"(
	"Id", "Name", "Manufacturer", "MedicineType", "Description", "IsPrescribed", "SideEffects", "RecommendedDose", "Intensity", "Quantity")
	VALUES (3, 'Amitriptilin', 'Hemofarm', 2, 'The drug is introduced into therapy based on the opinion of a psychiatrist or neuropsychiatrist or neurologist', true, 'There is no indication.', '3x1', 100, 10);
INSERT INTO public."Medicines"(
	"Id", "Name", "Manufacturer", "MedicineType", "Description", "IsPrescribed", "SideEffects", "RecommendedDose", "Intensity", "Quantity")
	VALUES (4, 'Panklav', 'Hemofarm', 2, 'Upper and lower respiratory tract infections (J00-J06.8; J20; J32; J40; J41; J42), Urogenital tract infections (N30, N34; N36; N37; N39), Middle ear infections (H65; H66).', true, 'The most common side effects with Panclav are diarrhea, nausea and vomiting.', '5x1', 200, 100);
INSERT INTO public."Medicines"(
	"Id", "Name", "Manufacturer", "MedicineType", "Description", "IsPrescribed", "SideEffects", "RecommendedDose", "Intensity", "Quantity")
	VALUES (5, 'Caffetine', 'Abela Pharm', 0, 'A combined preparation used for short-term therapy of acute, moderate pain.', false, 'No side effects.', '5x1', 500, 300);
