CREATE TABLE public."Allergies" (
    "Id" integer NOT NULL,
    "Medicine" text,
    "ReactionType" text,
    "ReactionTime" text
);


ALTER TABLE public."Allergies" OWNER TO root;

--
-- TOC entry 210 (class 1259 OID 33092)
-- Name: Allergies_Id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."Allergies" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Allergies_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 33185)
-- Name: AllergyPatient; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."AllergyPatient" (
    "AllergiesId" integer NOT NULL,
    "PatientsId" integer NOT NULL
);


ALTER TABLE public."AllergyPatient" OWNER TO root;

--
-- TOC entry 232 (class 1259 OID 33201)
-- Name: Appointments; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Appointments" (
    "Id" integer NOT NULL,
    "StartTime" timestamp without time zone NOT NULL,
    "PatientId" integer NOT NULL,
    "DoctorId" integer NOT NULL,
    "SurveyTaken" boolean NOT NULL,
    "Type" integer NOT NULL
);


ALTER TABLE public."Appointments" OWNER TO root;

--
-- TOC entry 231 (class 1259 OID 33200)
-- Name: Appointments_Id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."Appointments" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Appointments_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 33101)
-- Name: Buildings; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Buildings" (
    id integer NOT NULL,
    "Name" text,
    deleted boolean NOT NULL
);


ALTER TABLE public."Buildings" OWNER TO root;

--
-- TOC entry 212 (class 1259 OID 33100)
-- Name: Buildings_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."Buildings" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Buildings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 33109)
-- Name: Doctors; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Doctors" (
    "Id" integer NOT NULL,
    "DoctorType" integer NOT NULL,
    "Name" text,
    "Surname" text,
    "BirthDate" timestamp without time zone NOT NULL,
    "Jmbg" text,
    "Address" text,
    "Phone" text,
    "Email" text,
    "Username" text,
    "Password" text,
    "Gender" integer NOT NULL,
    "City" text,
    "Country" text,
    "UserType" integer NOT NULL,
    "Activated" boolean NOT NULL
);


ALTER TABLE public."Doctors" OWNER TO root;

--
-- TOC entry 214 (class 1259 OID 33108)
-- Name: Doctors_Id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."Doctors" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Doctors_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 33217)
-- Name: Equipments; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Equipments" (
    id integer NOT NULL,
    roomid integer,
    name text,
    "Amount" integer NOT NULL,
    deleted boolean NOT NULL
);


ALTER TABLE public."Equipments" OWNER TO root;

--
-- TOC entry 233 (class 1259 OID 33216)
-- Name: Equipments_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."Equipments" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Equipments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 33117)
-- Name: Feedbacks; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Feedbacks" (
    "Id" integer NOT NULL,
    "PersonId" integer NOT NULL,
    "Text" text,
    "Date" timestamp without time zone,
    "State" integer NOT NULL,
    "Anonymous" boolean NOT NULL,
    "Publish" boolean NOT NULL
);


ALTER TABLE public."Feedbacks" OWNER TO root;

--
-- TOC entry 216 (class 1259 OID 33116)
-- Name: Feedbacks_Id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."Feedbacks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Feedbacks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 33125)
-- Name: Floors; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Floors" (
    id integer NOT NULL,
    "FloorNumber" integer NOT NULL,
    deleted boolean NOT NULL
);


ALTER TABLE public."Floors" OWNER TO root;

--
-- TOC entry 218 (class 1259 OID 33124)
-- Name: Floors_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."Floors" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Floors_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 33131)
-- Name: Medicines; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Medicines" (
    "Id" integer NOT NULL,
    "Name" text,
    "Quantity" integer NOT NULL
);


ALTER TABLE public."Medicines" OWNER TO root;

--
-- TOC entry 220 (class 1259 OID 33130)
-- Name: Medicines_Id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."Medicines" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Medicines_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 33155)
-- Name: Patients; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Patients" (
    "Id" integer NOT NULL,
    "BloodType" integer NOT NULL,
    "RhFactor" integer NOT NULL,
    "Height" integer NOT NULL,
    "Weight" integer NOT NULL,
    "DoctorId" integer NOT NULL,
    "Blocked" boolean NOT NULL,
    "Malicious" boolean NOT NULL,
    "Name" text,
    "Surname" text,
    "BirthDate" timestamp without time zone NOT NULL,
    "Jmbg" text,
    "Address" text,
    "Phone" text,
    "Email" text,
    "Username" text,
    "Password" text,
    "Gender" integer NOT NULL,
    "City" text,
    "Country" text,
    "UserType" integer NOT NULL,
    "Activated" boolean NOT NULL
);


ALTER TABLE public."Patients" OWNER TO root;

--
-- TOC entry 226 (class 1259 OID 33154)
-- Name: Patients_Id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."Patients" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Patients_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 33139)
-- Name: Prescriptions; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Prescriptions" (
    "Id" integer NOT NULL,
    "MedicineName" text,
    "Quantity" integer NOT NULL,
    "Description" text,
    "RecommendedDose" text,
    "PrescriptionDate" text,
    "DoctorName" text,
    "PatientName" text,
    "PatientId" text,
    "TherapyStart" text,
    "TherapyEnd" text,
    "Diagnosis" text,
    "PharmacyName" text
);


ALTER TABLE public."Prescriptions" OWNER TO root;

--
-- TOC entry 222 (class 1259 OID 33138)
-- Name: Prescriptions_Id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."Prescriptions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Prescriptions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 33168)
-- Name: Rooms; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."Rooms" (
    id integer NOT NULL,
    floorid integer,
    "Name" text,
    "Description" text,
    "WorkHour" text,
    "DoctorId" integer,
    deleted boolean NOT NULL
);


ALTER TABLE public."Rooms" OWNER TO root;

--
-- TOC entry 228 (class 1259 OID 33167)
-- Name: Rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."Rooms" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Rooms_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 33147)
-- Name: SurveyQuestion; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."SurveyQuestion" (
    "Id" integer NOT NULL,
    "PersonId" integer NOT NULL,
    "QuestionText" text,
    "Rate" integer NOT NULL,
    "Category" integer NOT NULL
);


ALTER TABLE public."SurveyQuestion" OWNER TO root;

--
-- TOC entry 224 (class 1259 OID 33146)
-- Name: SurveyQuestion_Id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."SurveyQuestion" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."SurveyQuestion_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 33087)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO root;

--
-- TOC entry 3230 (class 2606 OID 33099)
-- Name: Allergies PK_Allergies; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Allergies"
    ADD CONSTRAINT "PK_Allergies" PRIMARY KEY ("Id");


--
-- TOC entry 3254 (class 2606 OID 33189)
-- Name: AllergyPatient PK_AllergyPatient; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."AllergyPatient"
    ADD CONSTRAINT "PK_AllergyPatient" PRIMARY KEY ("AllergiesId", "PatientsId");


--
-- TOC entry 3258 (class 2606 OID 33205)
-- Name: Appointments PK_Appointments; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Appointments"
    ADD CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id");


--
-- TOC entry 3232 (class 2606 OID 33107)
-- Name: Buildings PK_Buildings; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Buildings"
    ADD CONSTRAINT "PK_Buildings" PRIMARY KEY (id);


--
-- TOC entry 3234 (class 2606 OID 33115)
-- Name: Doctors PK_Doctors; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Doctors"
    ADD CONSTRAINT "PK_Doctors" PRIMARY KEY ("Id");


--
-- TOC entry 3261 (class 2606 OID 33223)
-- Name: Equipments PK_Equipments; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Equipments"
    ADD CONSTRAINT "PK_Equipments" PRIMARY KEY (id);


--
-- TOC entry 3236 (class 2606 OID 33123)
-- Name: Feedbacks PK_Feedbacks; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Feedbacks"
    ADD CONSTRAINT "PK_Feedbacks" PRIMARY KEY ("Id");


--
-- TOC entry 3238 (class 2606 OID 33129)
-- Name: Floors PK_Floors; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Floors"
    ADD CONSTRAINT "PK_Floors" PRIMARY KEY (id);


--
-- TOC entry 3240 (class 2606 OID 33137)
-- Name: Medicines PK_Medicines; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Medicines"
    ADD CONSTRAINT "PK_Medicines" PRIMARY KEY ("Id");


--
-- TOC entry 3247 (class 2606 OID 33161)
-- Name: Patients PK_Patients; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Patients"
    ADD CONSTRAINT "PK_Patients" PRIMARY KEY ("Id");


--
-- TOC entry 3242 (class 2606 OID 33145)
-- Name: Prescriptions PK_Prescriptions; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Prescriptions"
    ADD CONSTRAINT "PK_Prescriptions" PRIMARY KEY ("Id");


--
-- TOC entry 3251 (class 2606 OID 33174)
-- Name: Rooms PK_Rooms; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Rooms"
    ADD CONSTRAINT "PK_Rooms" PRIMARY KEY (id);


--
-- TOC entry 3244 (class 2606 OID 33153)
-- Name: SurveyQuestion PK_SurveyQuestion; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."SurveyQuestion"
    ADD CONSTRAINT "PK_SurveyQuestion" PRIMARY KEY ("Id");


--
-- TOC entry 3228 (class 2606 OID 33091)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3252 (class 1259 OID 33229)
-- Name: IX_AllergyPatient_PatientsId; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_AllergyPatient_PatientsId" ON public."AllergyPatient" USING btree ("PatientsId");


--
-- TOC entry 3255 (class 1259 OID 33230)
-- Name: IX_Appointments_DoctorId; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Appointments_DoctorId" ON public."Appointments" USING btree ("DoctorId");


--
-- TOC entry 3256 (class 1259 OID 33231)
-- Name: IX_Appointments_PatientId; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Appointments_PatientId" ON public."Appointments" USING btree ("PatientId");


--
-- TOC entry 3259 (class 1259 OID 33232)
-- Name: IX_Equipments_roomid; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Equipments_roomid" ON public."Equipments" USING btree (roomid);


--
-- TOC entry 3245 (class 1259 OID 33233)
-- Name: IX_Patients_DoctorId; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Patients_DoctorId" ON public."Patients" USING btree ("DoctorId");


--
-- TOC entry 3248 (class 1259 OID 33234)
-- Name: IX_Rooms_DoctorId; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Rooms_DoctorId" ON public."Rooms" USING btree ("DoctorId");


--
-- TOC entry 3249 (class 1259 OID 33235)
-- Name: IX_Rooms_floorid; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_Rooms_floorid" ON public."Rooms" USING btree (floorid);


--
-- TOC entry 3265 (class 2606 OID 33190)
-- Name: AllergyPatient FK_AllergyPatient_Allergies_AllergiesId; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."AllergyPatient"
    ADD CONSTRAINT "FK_AllergyPatient_Allergies_AllergiesId" FOREIGN KEY ("AllergiesId") REFERENCES public."Allergies"("Id") ON DELETE CASCADE;


--
-- TOC entry 3266 (class 2606 OID 33195)
-- Name: AllergyPatient FK_AllergyPatient_Patients_PatientsId; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."AllergyPatient"
    ADD CONSTRAINT "FK_AllergyPatient_Patients_PatientsId" FOREIGN KEY ("PatientsId") REFERENCES public."Patients"("Id") ON DELETE CASCADE;


--
-- TOC entry 3267 (class 2606 OID 33206)
-- Name: Appointments FK_Appointments_Doctors_DoctorId; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Appointments"
    ADD CONSTRAINT "FK_Appointments_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES public."Doctors"("Id") ON DELETE CASCADE;


--
-- TOC entry 3268 (class 2606 OID 33211)
-- Name: Appointments FK_Appointments_Patients_PatientId; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Appointments"
    ADD CONSTRAINT "FK_Appointments_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES public."Patients"("Id") ON DELETE CASCADE;


--
-- TOC entry 3269 (class 2606 OID 33224)
-- Name: Equipments FK_Equipments_Rooms_roomid; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Equipments"
    ADD CONSTRAINT "FK_Equipments_Rooms_roomid" FOREIGN KEY (roomid) REFERENCES public."Rooms"(id) ON DELETE RESTRICT;


--
-- TOC entry 3262 (class 2606 OID 33162)
-- Name: Patients FK_Patients_Doctors_DoctorId; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Patients"
    ADD CONSTRAINT "FK_Patients_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES public."Doctors"("Id") ON DELETE CASCADE;


--
-- TOC entry 3263 (class 2606 OID 33175)
-- Name: Rooms FK_Rooms_Doctors_DoctorId; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Rooms"
    ADD CONSTRAINT "FK_Rooms_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES public."Doctors"("Id") ON DELETE RESTRICT;


--
-- TOC entry 3264 (class 2606 OID 33180)
-- Name: Rooms FK_Rooms_Floors_floorid; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."Rooms"
    ADD CONSTRAINT "FK_Rooms_Floors_floorid" FOREIGN KEY (floorid) REFERENCES public."Floors"(id) ON DELETE RESTRICT;


--
-- TOC entry 3415 (class 0 OID 0)
-- Dependencies: 3414
-- Name: DATABASE hospitaldb; Type: ACL; Schema: -; Owner: postgres
--

GRANT ALL ON DATABASE hospitaldb TO root;


-- Completed on 2021-12-13 22:24:17

--
-- PostgreSQL database dump complete
--
INSERT INTO public."Allergies" VALUES (1, 'Penicilin', 'Stomach sickness', '10 seconds');
INSERT INTO public."Allergies" VALUES (2, 'Brufen', 'Heart ache', '15 minutes');
INSERT INTO public."Allergies" VALUES (3, 'Paracetamol', 'Dizzines', '1 hour');
INSERT INTO public."Allergies" VALUES (4, 'Panklav', 'Stomach ache and dizziness', '3 hour');
INSERT INTO public."Allergies" VALUES (5, 'Amitriptilin', 'Stomach sickness', '1 hour');


--
-- TOC entry 3415 (class 0 OID 33109)
-- Dependencies: 215
-- Data for Name: Doctors; Type: TABLE DATA; Schema: public; Owner: root
--

INSERT INTO public."Doctors" VALUES (1, 1, 'Ivan', 'Ivanovic', '1990-06-10 00:00:00', '651231133', 'Lasla Gala, 6.', '1331232', 'ivan@gmail.com', 'ivan', 'ivan', 0, 'Novi Sad', 'Serbia', 0, true);
INSERT INTO public."Doctors" VALUES (2, 1, 'Nikola', 'Slavnic', '1990-06-11 00:00:00', '111231133', 'Lasla Gala, 7.', '11231232', 'nikola@gmail.com', 'nikola', 'nikola', 0, 'Novi Sad', 'Serbia', 0, true);


--
-- TOC entry 3427 (class 0 OID 33155)
-- Dependencies: 227
-- Data for Name: Patients; Type: TABLE DATA; Schema: public; Owner: root
--

INSERT INTO public."Patients" VALUES (1, 0, 0, 180, 92, 2, false, false, 'Dajan', 'Jovanovic', '1990-06-11 00:00:00', '1234567890123', '15.Maj 48a', '060470540', 'slavkovranjes.gmail', 'kecman', 'lozinka', 0, 'Ruma', 'Serbia', 0, true);


--
-- TOC entry 3430 (class 0 OID 33185)
-- Dependencies: 230
-- Data for Name: AllergyPatient; Type: TABLE DATA; Schema: public; Owner: root
--

INSERT INTO public."AllergyPatient" VALUES (1, 1);
INSERT INTO public."AllergyPatient" VALUES (2, 1);
INSERT INTO public."AllergyPatient" VALUES (3, 1);


--
-- TOC entry 3432 (class 0 OID 33201)
-- Dependencies: 232
-- Data for Name: Appointments; Type: TABLE DATA; Schema: public; Owner: root
--

INSERT INTO public."Appointments" VALUES (1, '2021-12-30 07:00:00', 1, 2, false, 0);
INSERT INTO public."Appointments" VALUES (2, '2021-12-30 07:30:00', 1, 1, false, 0);
INSERT INTO public."Appointments" VALUES (3, '2021-12-30 08:00:00', 1, 1, false, 0);
INSERT INTO public."Appointments" VALUES (4, '2021-12-30 08:30:00', 1, 1, false, 0);
INSERT INTO public."Appointments" VALUES (5, '2021-12-30 09:00:00', 1, 1, false, 0);
INSERT INTO public."Appointments" VALUES (6, '2021-12-30 09:30:00', 1, 1, false, 0);


--
-- TOC entry 3413 (class 0 OID 33101)
-- Dependencies: 213
-- Data for Name: Buildings; Type: TABLE DATA; Schema: public; Owner: root
--



--
-- TOC entry 3419 (class 0 OID 33125)
-- Dependencies: 219
-- Data for Name: Floors; Type: TABLE DATA; Schema: public; Owner: root
--



--
-- TOC entry 3429 (class 0 OID 33168)
-- Dependencies: 229
-- Data for Name: Rooms; Type: TABLE DATA; Schema: public; Owner: root
--



--
-- TOC entry 3434 (class 0 OID 33217)
-- Dependencies: 234
-- Data for Name: Equipments; Type: TABLE DATA; Schema: public; Owner: root
--



--
-- TOC entry 3417 (class 0 OID 33117)
-- Dependencies: 217
-- Data for Name: Feedbacks; Type: TABLE DATA; Schema: public; Owner: root
--

INSERT INTO public."Feedbacks" VALUES (1, 1, 'Great service', '1990-06-11 00:00:00', 0, false, true);
INSERT INTO public."Feedbacks" VALUES (2, 1, 'Good customer care', '1990-06-11 00:00:00', 2, true, false);
INSERT INTO public."Feedbacks" VALUES (3, 1, 'Great equipment', '1990-06-11 00:00:00', 0, false, true);


--
-- TOC entry 3421 (class 0 OID 33131)
-- Dependencies: 221
-- Data for Name: Medicines; Type: TABLE DATA; Schema: public; Owner: root
--

INSERT INTO public."Medicines" VALUES (1, 'Brufen', 10);
INSERT INTO public."Medicines" VALUES (2, 'Aspirin', 10);


--
-- TOC entry 3423 (class 0 OID 33139)
-- Dependencies: 223
-- Data for Name: Prescriptions; Type: TABLE DATA; Schema: public; Owner: root
--

INSERT INTO public."Prescriptions" VALUES (111, 'Brufen', 10, 'Description', '2 times a day', '22.11.2021.', 'Branimir Nestorovic', 'Pera Peric', '1', '22.11.2021.', '22.11.2021.', 'Headache', 'Pharmacy1');
INSERT INTO public."Prescriptions" VALUES (112, 'Aspirin', 10, 'Description', '2 times a day', '22.11.2021.', 'Branimir Nestorovic', 'Pera Peric', '1', '22.11.2021.', '22.11.2021.', 'Headache', 'Pharmacy1');


--
-- TOC entry 3425 (class 0 OID 33147)
-- Dependencies: 225
-- Data for Name: SurveyQuestion; Type: TABLE DATA; Schema: public; Owner: root
--

INSERT INTO public."SurveyQuestion" VALUES (1, 1, 'How did you find the experience of booking appointments?', 4, 1);
INSERT INTO public."SurveyQuestion" VALUES (2, 1, 'Were our staff empathetic to your needs?', 3, 1);
INSERT INTO public."SurveyQuestion" VALUES (3, 1, 'How long did you have to wait until the doctor attends to you?', 4, 1);
INSERT INTO public."SurveyQuestion" VALUES (4, 1, 'Were you satisfied with the doctor you were allocated with?', 5, 1);
INSERT INTO public."SurveyQuestion" VALUES (5, 1, 'How easy is it to navigate our facility?', 2, 1);
INSERT INTO public."SurveyQuestion" VALUES (6, 1, 'How happy are you with the doctor’s treatment?', 1, 2);
INSERT INTO public."SurveyQuestion" VALUES (7, 1, 'Were we able to answer all your questions?', 2, 2);
INSERT INTO public."SurveyQuestion" VALUES (8, 1, 'How likely are you to recommend us to your friends and family?', 3, 2);
INSERT INTO public."SurveyQuestion" VALUES (9, 1, 'How much do you rate us?', 3, 2);
INSERT INTO public."SurveyQuestion" VALUES (11, 1, 'Did the pharmacy staff bill your health provider and collect the right deductible from you for your medicines?', 5, 3);
INSERT INTO public."SurveyQuestion" VALUES (12, 1, 'Did the radiology center provide the scan reports on the same day?', 4, 3);
INSERT INTO public."SurveyQuestion" VALUES (13, 1, 'Why should you conduct a patient satisfaction survey?', 5, 3);
INSERT INTO public."SurveyQuestion" VALUES (14, 1, 'How can you create a patient satisfaction questionnaire?', 1, 3);
INSERT INTO public."SurveyQuestion" VALUES (15, 1, 'Did you have any issues arranging an appointment?', 2, 3);
